#!/bin/bash
echo "=== CogniHire Production Status ==="
echo "Timestamp: $(date)"
echo ""
echo "Services Status:"
sudo systemctl is-active --quiet cognihire-backend && echo "✅ Backend: RUNNING" || echo "❌ Backend: STOPPED"
sudo systemctl is-active --quiet cognihire-frontend && echo "✅ Frontend: RUNNING" || echo "❌ Frontend: STOPPED"
sudo systemctl is-active --quiet nginx && echo "✅ Nginx: RUNNING" || echo "❌ Nginx: STOPPED"
echo ""
echo "Port Status:"
ss -tlnp | grep -q ":80 " && echo "✅ Port 80 (HTTP): OPEN" || echo "❌ Port 80 (HTTP): CLOSED"
ss -tlnp | grep -q ":8000 " && echo "✅ Port 8000 (Backend): OPEN" || echo "❌ Port 8000 (Backend): CLOSED"
ss -tlnp | grep -q ":3000 " && echo "✅ Port 3000 (Frontend): OPEN" || echo "❌ Port 3000 (Frontend): CLOSED"
echo ""
echo "Endpoint Tests:"
curl -s --max-time 5 http://localhost/api/ > /dev/null && echo "✅ API Endpoint: RESPONDING" || echo "❌ API Endpoint: NOT RESPONDING"
curl -s --max-time 5 -I http://localhost | head -1 | grep -q "200" && echo "✅ Frontend Endpoint: RESPONDING" || echo "❌ Frontend Endpoint: NOT RESPONDING"
echo ""
echo "=== End of Report ==="